### ISSUE TITLE
Optimized Functions Plans

### ISSUE THREAD

**Issue by cblappert** [facebook/prepack#2337]
Planning for optimized functions (original issue #799) mostly for H2 2018, but some stuff for past then. Under each category, the items are in rough order of priority

Anything *italicized* is wishlist and is not currently a priority.

Anything with a :small_orange_diamond: in front is 2nd priority once all unmarked items are completed.

- Correctness
  - Nested Optimized Functions
    - [ ] Become confident in correctness of output
      - possibly look into extending @calebmer's fuzzer
    - [ ] Nested `__optimize` calls #1398
  - Bindings
    - [ ] Havoc Bugs
      - [ ] Fix initialization of bindings used by havoc #2335
      - [ ] Fix havocing of templates within optimized functions #2217
    - [ ] Optimized functions capturing bindings of residual functions
    - [ ] Captured bindings for nested optimized functions #1615
  - General Bugfixes
    - [ ] Make sure all outstanding invariant failures on React Fusion are gone
      - #2252
      - [ ] [React Compiler Optimized Function Bugs](https://github.com/facebook/prepack/issues?q=is%3Aissue+label%3A%22optimized+functions%22+is%3Aopen+label%3Abug+label%3A%22react+compiler%22)
      - [ ] [All Optimized Function Bugs]( https://github.com/facebook/prepack/issues?q=is%3Aissue+label%3A%22optimized+functions%22+is%3Aopen+label%3Abug)
    - [ ] :small_orange_diamond: Proper support for possible exceptions (with @hermanventer)
- Enhancements
  - [ ] Add option to optimize functions at the site of the `__optimize` call #2336
    - for supporting calls inside of `map` and `filter`
  - [ ] Investigation: Talk to @NTillman to understand asks for Instant Render
  - :small_orange_diamond: Code Bloat
    - [ ] eliminate redundant unobservable intermediate states of properties/bindings
    - [ ] #2276 correct precise capture of bindings
  - [ ] :small_orange_diamond: Add support for usage of `this` in optimized functions #1640
  - [ ] _add compatibility for lazy initialization_
  - [ ] _add support for bound functions #2213_
  - [ ] _widen when optimized functions have side-effects #1750_
- Better Engineering
  - [ ] Stop applying/reverting effects in serializer multiple times per optimize function
    - Probably will be done as a part of @hermanventer's refactor
  - [ ] _Enhance serializer tests using automated heap traversal #1852_
